### ISSUE TITLE
Setting up the kanban board for the group capstone project

### ISSUE THREAD

**Issue by JonahKayizzi** [JonahKayizzi/Javascript-Capstone-Pokemon-API#21]
The kanban board for this project has been set up in this [link](https://github.com/users/JonahKayizzi/projects/3) using GitHub projects.

This project has two collaborators @d4nQw3rty  & @JonahKayizzi .

**Comment by brytebee** [comment]
Hi, @ 👋,

##

### Highlights💡
- The team number is specified.✔️ 
- The project kanban link is supplied.✔️
- The cards are shared fairly among team members.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- N/A

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
